name: covidscreen
version: 0.3.0-nullsafety.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  fhir: ^0.3.0-nullsafety.0
  fhir_at_rest: ^0.3.0-nullsafety.0
  fhir_auth: 
    path: ../../fhir/fhir_auth
  flutter:
    sdk: flutter
  oauth2: ^1.6.3
  url_launcher: ^6.0.2

dependency_overrides:
  http: ^0.11.0