name: simple_covid_screen
version: 0.3.0-nullsafety.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  fhir: ^0.3.0-nullsafety.0
  fhir_at_rest: ^0.3.0-nullsafety.0
  fhir_auth: ^0.3.0-nullsafety.5
  flutter:
    sdk: flutter